# Required: local settings
local:
  root_dir : <%= ENV['GITHUB_WORKSPACE'] %>

# Required: deployment targets
targets:
  - type     : "bintray"
    user     : <%= ENV['BINTRAY_USER'] %>
    password : <%= ENV['BINTRAY_PASS'] %>

# Required: packages to be deployed
packages:
  - repo     : "snowplow-generic"
    name     : "cla-bot"
    user_org : "snowplow"
    publish  : true
    override : false
    continue_on_conflict : false
    version  : <%= ENV['SBT_VERSION'] %>
    build_version : <%= ENV['TAG_VERSION'] %>
    build_commands:
      - sbt assembly

    # Required: Artifact
    artifacts:
      - prefix : "cla-bot-assembly-"
        suffix : ".jar"
        type   : "asis"

        # The binaries to put in the zip
        binary_paths:
          - target/scala-2.12/cla-bot-assembly-{{ packages.0.version }}.jar